####
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lambda-user-role-binding
  namespace: default
subjects:
- kind: User
  name: lambda
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: lambda-access
  apiGroup: rbac.authorization.k8s.io
